[package]
name = "wasm"
version = "0.1.0"
authors = ["QiroNT"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.82"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

image = "0.23.14"
img_hash = "3.2.0"
hex = "0.4.3"

[dev-dependencies]
wasm-bindgen-test = "0.3.32"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true
